def f():
    pass


import time

test = {
    "/path": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat5y5hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paty5yhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patuiik8lii7uhthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paiulkuthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathftr5h": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa5tthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patf4hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pagrft8k8khh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pag5thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat8ikikhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat8iihh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patk8ik8hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa8k8kthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/path8k8kuh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patiluhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat87ikuikhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patlk8o8o98hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paik89o9thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patiuklikhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa8o899othh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paukukthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patu6uhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat89o8o8hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patu6u6hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat8i87ihh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pai88ithh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paikuikthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pai8k8ik8thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paikuk8thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/path68h": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patwerhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawe34rrthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pwerathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawee34erthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawertthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pwerwerathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pahgthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathhe23e": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat435werhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa23s23e2thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pae2ethh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsdcschh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/wpathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/psathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathewhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa23thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pau6uthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa4wthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa342thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat6u6uhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/p34athh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa2thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paililthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathikikulh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathklih": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patululhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/ililpathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pauluthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patulhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patukuhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paukuklthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathdwdh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patdwdhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patdwdw43hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa34r3y65ythh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa34thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa5y5thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pa56y5thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathsfeh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pahfrthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pathaah": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/p5athh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pat45thh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paetethh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/peathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawefwthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paweeethh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawethh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paweethh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pafegthh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsddewhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patefeREhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pasdsathh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfsfsashh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patswerfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pate5tqfesfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patertresfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pawerwtwertsfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf344shh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/paterewrtsfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfswerhh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patfesfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patwdsfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfershh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfdfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsr33rfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsffe34shh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patseffdfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patseffeffshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsef34rfefshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsretertu7fshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfsh87ki8h": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsjujfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfsiyj8khh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsjyyjfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pjyyatsfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patyjyjsfshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pats78fshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsj7fshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfirt8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf87i56i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfii8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi88ku7hh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi6u8i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf64yi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfeyi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf6y54yi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsetyfi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfierysdft8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi86erkshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfiyety8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfiey8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfirty8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patseyfi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfieryuj8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfiujr8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi8kretyshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfyi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfuyi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfirgf8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfferfi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi8ferkshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfiad8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi8eedkshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi8k34shh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi8kwershh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi834kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf5i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf456i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf6i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsf546i8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pats345fi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/pats123fi8kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
    "/patsfi812kshh": {"GET": f, "POST": f, "DELETE": f, "UPDATE": f},
}

# start = time.time()
# a = test["/patsfirgf8kshh"]["UPDATE"]
# b = test["/patsf344shh"]["POST"]
# c = test["/patsfierysdft8kshh"]["GET"]
# d = test["/patdwdhh"]["DELETE"]
# e = test["/pauluthh"]["POST"]
# end = time.time()
# print(start)
# print(end)



class PathObj:
    def __init__(self, path):
        self.path = path


a = PathObj("/")
print(a.__dict__.get("pasth",None))